import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'


const PaymentSuccess: NextPage = () => {
  const router = useRouter()
  const { amount } = router.query

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Purchase Successful
        </h1>

        <p className={styles.description}>
            You purchased {amount} USDC
        </p>

        
      </main>
    </div>
  )
}

export default PaymentSuccess
