import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import createReservation from '../components/utils/wyre/createReservation'
import KYCauth from "../components/utils/wyre/KYCauth";
import { useRouter } from 'next/router'
import renderPaymentWidget from '../components/utils/wyre/renderPaymentWidget'



const Home: NextPage = () => {
  const [publicKey, setPublicKey] = useState("")
  const [email, setEmail] = useState("")
  const [amount, setAmount] = useState("10")


  const onBuyClick = (event: React.MouseEvent<HTMLElement>) => {
    event.preventDefault();
    if(parseInt(amount) > 100){
      
      KYCauth(publicKey, amount)

    } else {
      createReservation(publicKey, amount).then(res => {
        renderPaymentWidget(res.reservation)

        // router.push({
        //   pathname: '/paymentSuccess/[amount]',
        //   query: { amount: paymentSuccessAmount }
        // })
      })
    }
  } 

  return (
    <div className={styles.container}>
      {/* Testing API */}
      <Script src="https://verify.testwyre.com/js/verify-module-init-beta.js"></Script>

      {/* Production API */}
      {/* <Script src="https://verify.sendwyre.com/js/verify-module-init-beta.js"></Script> */}
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <div id="wyre-dropin-widget-container"></div>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Etherlands Wyre Widget
        </h1>

        <form>
          <p className={styles.description}>
            Buy USDC with FIAT
          </p>

          <div className={styles.grid}>
            <div className={styles.card}>
                <label>Email Address:</label>
                <input type="email" required placeholder="etherlands@gfx.io" onChange={e => setEmail(e.target.value)}/>
              </div>

              <div className={styles.card}>
                <label>Amount:</label>
                <input type="text" required defaultValue="10" onChange={e => setAmount(e.target.value)}/>
              </div>

              <div className={styles.card}>
                <label>Ethererum public key:</label>
                <input type="text" required placeholder="0x..." onChange={e => setPublicKey(e.target.value)}/>
              </div>
              
            </div>

            <button id='buy' type="submit" onClick={onBuyClick}>Buy</button>
          </form>
      </main>
    </div>
  )
}

export default Home
